"""Switch registry: every module-level switch and user setting in the Lua code, with its default, where it lives and what
its own comment says, plus a STATUS column from the desk (verve_desk/docs/switch_status.json: name -> "status | why | when").
Generated, so it never drifts from the code: re-run after any change and before a release.

Covers R.* (racecraft / recovery / troublespots...), H.* (human), D.* (drivers, difficulty), S.* (strategy), T.*, F.* upper-case fields
and the user settings in Verve.lua's DEFAULTS. K.* / CV.* tuning constants are counted, not listed (see the code).

    python tools/switch_registry.py                 # writes verve_desk/docs/SWITCHES.md
    python tools/switch_registry.py --stdout        # print instead
"""
import argparse
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DESK = os.path.join(os.path.expanduser("~"), "Documents", "Assetto Corsa", "verve_desk", "docs")
FIELD = re.compile(r"^(R|H|D|T|F|S)\.([A-Z][A-Z0-9_]*)\s*=\s*(.*?)\s*(?:--\s?(.*))?$")
CONT = re.compile(r"^\s+--\s?(.*)$")


def scan(path):
    rows, lines = [], open(path, encoding="utf-8", errors="replace").read().splitlines()
    for n, line in enumerate(lines):
        m = FIELD.match(line)
        if not m:
            continue
        pre, name, val, com = m.groups()
        com = [com] if com else []
        k = n + 1
        while k < len(lines) and CONT.match(lines[k]) and not FIELD.match(lines[k]):
            com.append(CONT.match(lines[k]).group(1)); k += 1
        rows.append({"name": f"{pre}.{name}", "default": val.rstrip(","), "file": os.path.relpath(path, ROOT).replace(os.sep, "/"),
                     "line": n + 1, "comment": " ".join(c.strip() for c in com)})
    return rows


def settings():
    txt = open(os.path.join(ROOT, "Verve.lua"), encoding="utf-8", errors="replace").read()
    m = re.search(r"local DEFAULTS = \{(.*?)\n\}", txt, re.S)
    out = []
    for part in re.finditer(r"(\w+)\s*=\s*([^,\n]+),?\s*(?:--\s?([^\n]*))?", m.group(1) if m else ""):
        out.append({"name": f"setting {part.group(1)}", "default": part.group(2).strip(), "file": "Verve.lua", "line": 0,
                    "comment": (part.group(3) or "").strip()})
    return out


def auto_status(r):
    c = r["comment"]
    m = re.search(r"DEFAULT (0\.\d+\.\d+)", c)
    if m:
        return f"default since {m.group(1)}"
    if re.search(r"harness|A/B|\(A/B\)|switch", c, re.I):
        return "experimental (harness switch)"
    return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true")
    a = ap.parse_args()
    status = {}
    sp = os.path.join(DESK, "switch_status.json")
    if os.path.exists(sp):
        status = json.load(open(sp, encoding="utf-8"))
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "lib", "*.lua"))) + [os.path.join(ROOT, "Verve.lua")]:
        rows += scan(f)
    rows += settings()
    consts = sum(len(re.findall(r"^(?:K|CV)\.[A-Z]", open(f, encoding="utf-8", errors="replace").read(), re.M))
                 for f in glob.glob(os.path.join(ROOT, "lib", "*.lua")))
    out = ["# Verve switch registry", "",
           "Generated by `tools/switch_registry.py` from the code - do not edit by hand. STATUS comes from",
           "`verve_desk/docs/switch_status.json` (the decision) or, failing that, the code comment. Decisions: `decisions/`.", "",
           f"{len(rows)} switches and settings; {consts} K.* / CV.* tuning constants not listed.", "",
           "| Switch | Default | Status | Where | What the code says |", "|---|---|---|---|---|"]
    for r in rows:
        st = status.get(r["name"]) or auto_status(r)
        where = f"{r['file']}:{r['line']}" if r["line"] else r["file"]
        com = r["comment"].replace("|", "/")
        if len(com) > 220:
            com = com[:217] + "..."
        out.append(f"| `{r['name']}` | `{r['default'][:30]}` | {st} | {where} | {com} |")
    text = "\n".join(out) + "\n"
    if a.stdout:
        print(text)
    else:
        os.makedirs(DESK, exist_ok=True)
        open(os.path.join(DESK, "SWITCHES.md"), "w", encoding="utf-8").write(text)
        print(f"wrote {os.path.join(DESK, 'SWITCHES.md')}: {len(rows)} rows")


if __name__ == "__main__":
    main()
